<?php 
/**
 * Base Layout
 *
 * This base layout it's used to separate the HTML 
 * blocks of the page, specially the ones that
 * can be override by inner templates
 *
 * @package Ziemes
 */
?><!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Ziemes <?= isset ($title) ? ('| ' . $this->e($title)) : "" ?></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <?=$this->section('stylesheets')?>
        
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <!-- Add your site or application content here -->
        <?= $this->section('content') ?>
        
        <?= $this->section('javascripts') ?>

    </body>
</html>
