<?php // This is our layout ?>
<?php $this->layout('layouts::base') ?>

<?php $this->start('stylesheets') ?>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/4.2.0/normalize.min.css">
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
    <style>
        
        html, body {
            height: 100%;
        }
        
        body {
            background-color: #eee;
        }
        
        .main-content {
            max-width: 76rem;
            height: 100%;
            margin: 0 auto;
            padding: 2rem;
            background-color: white;
        }
        
        .sidebar {
            height: 100%;
            background-color: #aa0;
        }
        
        
    </style>
<?php $this->stop() ?>


<div class="main-content">
    <div class="pure-g">
        <div class="pure-u-2-3">
            <?=$this->section('content')?>
        </div>
        <div class="pure-u-1-3">
            <?=$this->section('sidebar')?>
        </div>
    </div>
</div>


